// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async loadSettings() : Promise<AppSettings> {
    return await TAURI_INVOKE("load_settings");
},
async saveSettings(settings: AppSettings) : Promise<null> {
    return await TAURI_INVOKE("save_settings", { settings });
},
/**
 * Sends a native system notification.
 * On mobile platforms, returns an error as notifications are not yet supported.
 */
async sendNativeNotification(title: string, body: string | null) : Promise<null> {
    return await TAURI_INVOKE("send_native_notification", { title, body });
},
async getConfigDir() : Promise<string> {
    return await TAURI_INVOKE("get_config_dir");
},
async getLogsDir() : Promise<string> {
    return await TAURI_INVOKE("get_logs_dir");
},
async showDashboardWindow() : Promise<null> {
    return await TAURI_INVOKE("show_dashboard_window");
},
async closeDashboardWindow() : Promise<null> {
    return await TAURI_INVOKE("close_dashboard_window");
},
async showMainWindow(title: string | null) : Promise<null> {
    return await TAURI_INVOKE("show_main_window", { title });
},
async closeMainWindow() : Promise<null> {
    return await TAURI_INVOKE("close_main_window");
},
async getAppInfo() : Promise<[string, string]> {
    return await TAURI_INVOKE("get_app_info");
},
async getBuilds() : Promise<GetBuildsResponse> {
    return await TAURI_INVOKE("get_builds");
},
async getAlerts() : Promise<GetAlertsResponse> {
    return await TAURI_INVOKE("get_alerts");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Alert = { id: string; subject: string; priority: AlertPriority; category: AlertCategory; alertMessage: string; trigger: string; fixed: boolean; ctime: string; ackTime: string }
export type AlertCategory = "SYSTEM" | "METRIC"
export type AlertPriority = "LOW" | "MEDIUM" | "HIGH"
export type AppSettings = { enable_notifications?: boolean; notifications_total?: number; theme?: AppTheme; server_url?: string; user?: string; token?: string; poll_interval_in_secs?: number; paused?: boolean }
export type AppTheme = "system" | "light" | "dark"
export type Build = { id: string; configuration: string; configurationPath?: string; masterNodeAddress: string; requester: string; requesterName?: string | null; canceller?: string | null; cancellerName?: string | null; version: string; status: BuildStatus; beginDate: string; statusDate?: string | null; duration: string; waitDuration: string }
export type BuildStatus = "SUCCESSFUL" | "RECOMMENDED" | "FAILED" | "CANCELLED" | "TIMEOUT" | "RUNNING"
export type GetAlertsResponse = { alerts: Alert[]; error: string | null; lastPollingTime?: string | null }
export type GetBuildsResponse = { builds: Build[]; error: string | null; lastPollingTime?: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
