use specta_typescript::BigIntExportBehavior;
use tauri_specta::{Builder, collect_commands};

use crate::commands::alerts::{self, GetAlertsResponse};
use crate::commands::builds::GetBuildsResponse;
use crate::path;

use crate::commands::{app, builds, settings, windows};
use crate::types::alert::{Alert, AlertCategory, AlertPriority};
use crate::types::build::Build;
use crate::types::settings::AppSettings;

pub fn generate_bindings() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            settings::load_settings,
            settings::save_settings,
            // notifications::send_native_notification,
            path::get_config_dir,
            path::get_logs_dir,
            windows::show_dashboard_window,
            windows::close_dashboard_window,
            windows::show_main_window,
            windows::close_main_window,
            app::get_app_info,
            builds::get_builds,
            alerts::get_alerts,
        ])
        .error_handling(tauri_specta::ErrorHandlingMode::Throw)
        .typ::<AppSettings>()
        .typ::<Build>()
        .typ::<GetBuildsResponse>()
        .typ::<Alert>()
        .typ::<AlertPriority>()
        .typ::<AlertCategory>()
        .typ::<GetAlertsResponse>()
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo test export_bindings -- --ignored
pub fn export_ts_bindings(builder: &Builder<tauri::Wry>) {
    builder
        .export(
            specta_typescript::Typescript::default()
                .bigint(BigIntExportBehavior::String)
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings(&generate_bindings());
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
