use tauri_specta::{Builder, collect_commands};

use crate::{notifications, path, settings};

// use crate::notifications;
// use crate::preferences;
// use crate::window;

pub fn generate_bindings() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            settings::load_settings,
            settings::save_settings,
            notifications::send_native_notification,
            path::get_config_dir,
            path::get_logs_dir,
            // window::open_external_url,
            // recovery::save_emergency_data,
            // recovery::load_emergency_data,
            // recovery::cleanup_old_recovery_files,
            // quick_pane::show_quick_pane,
            // quick_pane::dismiss_quick_pane,
            // quick_pane::toggle_quick_pane,
            // quick_pane::get_default_quick_pane_shortcut,
            // quick_pane::update_quick_pane_shortcut,
        ])
        .error_handling(tauri_specta::ErrorHandlingMode::Throw)
        .typ::<settings::AppSettings>()
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo test export_bindings -- --ignored
pub fn export_ts_bindings(builder: &Builder<tauri::Wry>) {
    builder
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings(&generate_bindings());
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
